### PR TITLE
feat(multiple): Added ability to message multiple people

### PR DESCRIPTION
**Pull request by danielhumgon**
PR related to this trello task --> https://trello.com/c/xyix43LT

### CODE REVIEW

**Comment by danielhumgon** [comment]
This is no longer a work in progress, is ready for @christroutner to review

**Comment by danielhumgon** [comment]
This is no longer a work in progress, is ready for @christroutner to review

**Comment by christroutner** [comment]
Screenshot from 2021-01-03 08-32-24

**Comment by christroutner** [comment]
I am seeing this error when loading the changes in my browser:
```
Failed prop type: The prop `bchWallet` is marked as required in `SignMessage`, but its value is `null`.
```

**Review by christroutner — APPROVED** [review]

**Comment by christroutner** [comment]
:tada: This PR is included in version 1.21.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
